---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.10"
          - "3.9"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Pip Packages
        run: pip install -U -- mypy toml

      - name: Pip Packages 2
        shell: python
        run: |-
          from os import execl
          from pathlib import Path
          from sys import executable
          from toml import loads
          path = Path.cwd() / "pyproject.toml"
          toml = loads(path.read_text())
          deps = toml["project"]["dependencies"]
          execl(executable, executable, "-m", "pip", "install", "--", *deps)


      - name: Lint
        run: mypy -- .

      - name: Install
        run: pip3 install -- .
