---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.11"
          - "3.10"
          - "3.9"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Install Pip Packages
        shell: python
        run: |-
          from itertools import chain
          from os import execl
          from sys import executable

          from tomllib import load

          with open("pyproject.toml", "rb") as fd:
              toml = load(fd)
          project = toml["project"]
          execl(
              executable,
              executable,
              "-m",
              "pip",
              "install",
              "--upgrade",
              "--",
              *project["dependencies"],
              *chain.from_iterable(project["optional-dependencies"].values()),
          )

      - name: Lint
        run: mypy -- .

      - name: Install
        run: pip3 install -- .
